name: Build Tests

on: [pull_request]

jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {
            name: "Windows/X64/",
            os: windows-latest,
            args: -G "Visual Studio 17 2022" -A x64,
          }
          - {
            name: "Windows/X86/",
            os: windows-latest,
            args: -G "Visual Studio 17 2022" -A x86,
          }
    steps:
      - uses: actions/checkout@v3
      - name: Bulid
        run: |
          Build.bat
